title: Saurab Mishra
logo: /assets/img/profile-pic(1).png
description: Data Scientist | Machine Learning Engineer | AI Enthusiast
show_downloads: true
theme: jekyll-theme-minimal

# Social links
github_username: SaurabMishra12
linkedin_username: saurab-mishra-493a73178

# Additional settings
google_analytics: # Add your Google Analytics tracking ID here
plugins:
  - jekyll-seo-tag

# Navigation
nav:
  - {name: 'Home', link: '/'}
  - {name: 'Projects', link: '/projects'}
  - {name: 'Experience', link: '/experience'}
  - {name: 'Education', link: '/education'}
  - {name: 'Certifications', link: '/certifications'}
  - {name: 'Contact', link: '/contact'}
