title: Saurab Mishra
logo: /assets/img/profile-pic(1).png
description: Data Scientist | AI Researcher | Machine Learning Engineer | AI Systems Enthusiast
show_downloads: true
theme: jekyll-theme-architect

# Social links
github_username: SaurabMishra12
linkedin_username: saurab-mishra-493a73178

# Additional settings
google_analytics: UA-XXXXXXXXX-X
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Navigation
nav:
  - {name: 'Home', link: '/'}
  - {name: 'Projects', link: '/projects'}
  - {name: 'Research', link: '/research'}
  - {name: 'Experience', link: '/experience'}
  - {name: 'Education', link: '/education'}
  - {name: 'Certifications', link: '/certifications'}
  - {name: 'Contact', link: '/contact'}

# Footer
footer:
  - {name: 'Terms', link: '/terms'}
